### ISSUE TITLE
REPL - serialization bug when creating objects

### ISSUE THREAD

**Issue by rubanm** [twitter/scalding#1170]
This was reported internally. One symptom is Mode not getting picked up correctly when the job runs, even though it's set to hdfs in the REPL. Occurs for certain closures that reference outer vals.

E.g.
```
Caused by: java.lang.RuntimeException: TestTapFactory doesn't support mode: Local(false)
	at com.twitter.scalding.TestTapFactory.createTap(TestTapFactory.scala:105)
	at com.twitter.scalding.commons.source.VersionedKeyValSource.createTap(VersionedKeyValSource.scala:136)
	at com.twitter.scalding.Source.read(Source.scala:109)
	at com.twitter.scalding.typed.TypedPipe$$anonfun$from$1.apply(TypedPipe.scala:50)
	at com.twitter.scalding.typed.TypedPipe$$anonfun$from$1.apply(TypedPipe.scala:49)
	at com.twitter.scalding.typed.TypedPipeFactory$$anonfun$4.apply(TypedPipe.scala:672)
	at com.twitter.scalding.typed.TypedPipeFactory$$anonfun$4.apply(TypedPipe.scala:668)
```

Test cases to repro:
```scala
:paste

import com.twitter.scalding.commons.source.VersionedKeyValSource
import com.twitter.scalding._
import com.twitter.scalding.typed.TDsl._

object SimpleTestFail { 
  val count = 1L 
  VersionedKeyValSource[Array[Byte], Array[Byte]]("/path/to/source")
   .map { x => count }
   .groupAll
   .sum
   .dump
}

object SimpleTestShouldNotFail { 
  VersionedKeyValSource[Array[Byte], Array[Byte]]("/path/to/source")
   .map { x => 
     val count = 1L 
     count
   }
   .groupAll
   .sum
   .dump
}

object SimpleTestFail2 { 
   val count = 1L 
  VersionedKeyValSource[Array[Byte], Array[Byte]]("/path/to/source")
   .map { x => 
     val count2 = count
     count2
   }
   .groupAll
   .sum
   .dump
}

ctrl + D

SimpleTestFail // should fail 
SimpleTestShouldNotFail // should not fail, outputs something like ((),144851)
SimpleTestFail2 // fails too, outer referencing also doesn't matter
```

**Comment by perryzheng** [comment]
Yay reported by me. :)
