### ISSUE TITLE
Scalding, Parquet, Thrift, and Scrooge: Column Projection is Wonky

### ISSUE THREAD

**Issue by Gastove** [twitter/scalding#1202]
I have a file called common.thrift that defines types and structs we use all over the place. It looks a bit like this:

```
typedef string ID

enum IdType {
  APID = 1,
  UDID = 2
}

struct Identity {
  1: Id id
  2: IdType id_type
}
```
Then we have a record of an app open, so:

```
include "common.thrift"

struct Open {
  1: common.Identity identity
  2: common.ID app_id
}
```

I'm compiling my thrift definitions with Scrooge 3.16.3 for Scala 2.10.x and libthrift for Java. 

For my next trick, I use a Cascading job to generate a big ol' pile of Thrift objects, stored in Parquet. This goes swimmingly. Now, over in Scala-land again, I define a source for my Thrift objects:

```
case class Opens(
  path: String,
  override val withFilter: Option[FilterPredicate] = None,
  override val withColumns: Set[String] = Set()
) extends FixedPathParquetScrooge[Open](path)
```

And try to read it, using column projection, in roughly the simplest way possible:

```
class PrintOpens(args: Args) extends Job(args) {

  val path = // path to parquet file in hdfs
  TypedPipe.from(Opens(path, withColumns=Set("identity/**")))
    .map{ o => o.identity.id }
    .write(TypedTsv(conf.getString("output_root") + "/column_subselect_out"))
}
```

When I try to run this (using `hadoop jar my-shaded-jar.jar com.twitter.scalding.Tool com.my.jar.PrintOpens --hdfs`), I get:

```
Caused by: parquet.io.InvalidRecordException: required group identity = 1 {
  required binary id (UTF8) = 1;
  required binary id_type (ENUM) = 2;
  required int32 id_type = 2;
} found: expected optional group identity {
  optional binary id (UTF8);
  optional binary id_type (ENUM);
}
```

Thoughts?

**Comment by isnotinvain** [comment]
Now that I look at this -- I'm curious what happens if you throw "required" or "optional" in front of all your fields? Thrift has a strange third case of "neither required not optional" -- maybe we are handling this wrong. @tsdeng do you recognize this?

**Comment by Gastove** [comment]
Just tested `required`; can test `optional` next. Worth pointing out: all of my thrift stuff was generated without either of those modifiers; might have to regenerate some data, test with that.

**Comment by tsdeng** [comment]
This problem was addressed in parquet master already. It's just not been released.
It's triggered when you have fields that are not "optional" nor "required".
If you annotate your fields explicitly with "optional" or "required", this problem should go away

**Comment by Gastove** [comment]
I assume my data needs to be _generated_ with thrift definitions that annotate `optional` or `required`? Just adding `required` after the fact makes no difference; switching to `optional` makes enough of a difference in my code that I'm still cleaning everything up to do a test run.

**Comment by Gastove** [comment]
@tsdeng any idea when this fix will be released?

**Comment by tsdeng** [comment]
Yes I think you may need to regenerate the data to avoid the differences of requirement type between schemas used for reading and writing. For the release schedule question I would ask response from @isnotinvain and @julienledem

**Comment by Gastove** [comment]
welp.

**Comment by Gastove** [comment]
Ooookay. A long set of cluster mis-adventures has kept me from working on this. Now I've got a new set of problems -- similar, yet different.

Using: Scalding 0.15.0, parquet-mr 1.7, libthrift 0.91, Java 7, Scrooge 3.19.0

What I observe is that I cannot project nested thrift objects -- only top-level fields. The M/R job _will run without error_, but every object will be empty. So, for instance:

```
// devcie_identity.thrift
typedef string UUID

enum Platform {
  ANDROID = 1,
  IOS = 2
}

struct DeviceIdentity {
  1: required UUID id
  2: required string name
  3: required Platform platform
}

// open.thrift
include common.thrift

struct Open {
  1: required DeviceIdentity device_identity
  2: required i64 timestamp
}
```

This is the same as above, but I'll copy here for easy of reading:
```
// Opens.scala
case class Opens(
  path: String,
  override val withFilter: Option[FilterPredicate] = None,
  override val withColumns: Set[String] = Set()
) extends FixedPathParquetScrooge[Open](path)

// The actual job
class PrintOpens(args: Args) extends Job(args) {

  val path = // path to parquet file in hdfs
  val cols = Set("device_identity")

  TypedPipe.from(Opens(path, withColumns=cols))
    .map{ o => o.deviceIdentity.id }
    .write(TypedTsv(conf.getString("output_root") + "/column_subselect_out"))
}
```

With the above, every open that goes by will be empty:
```
Open(DeviceIdentity(), )
```

But if I set `val cols = Set("timestamp")`, I get timestamps out. I've tried setting `cols` to a variety of different values -- `open.device_identity`, `device_identity.*`, `device_identity.id`. No change.

I should note: I'm reading the projection docs from [here](https://github.com/apache/parquet-mr/blob/f4e754e66e3661274df624bc328991cd88dd03d6/parquet_cascading.md). If I try the old-style `val cols = Set("device_identity/**")`, I get:

```
Caused by: parquet.io.InvalidRecordException: required int32 platform = 3 found: expected required binary platform (ENUM)
        at parquet.schema.PrimitiveType.checkContains(PrimitiveType.java:495)
        at parquet.schema.GroupType.checkGroupContains(GroupType.java:316)
        at parquet.schema.GroupType.checkContains(GroupType.java:306)
        at parquet.schema.GroupType.checkGroupContains(GroupType.java:316)
        at parquet.schema.MessageType.checkContains(MessageType.java:124)
        at parquet.hadoop.api.ReadSupport.getSchemaForRead(ReadSupport.java:55)
        at parquet.hadoop.thrift.ThriftReadSupport.init(ThriftReadSupport.java:113)
        at parquet.hadoop.ParquetInputFormat.getSplits(ParquetInputFormat.java:274)
        at parquet.hadoop.mapred.DeprecatedParquetInputFormat.getSplits(DeprecatedParquetInputFormat.java:48)
        at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:200)
        at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:134)
        at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1060)
        at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1052)
        at org.apache.hadoop.mapred.JobClient.access$500(JobClient.java:173)
        at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:934)
        at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:885)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
        at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:885)
        at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:859)
        at cascading.flow.hadoop.planner.HadoopFlowStepJob.internalNonBlockingStart(HadoopFlowStepJob.java:108)
        at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:217)
        at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:160)
        at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
        at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by johnynek** [comment]
@tsdeng @isnotinvain any comments on this one?
