### ISSUE TITLE
java.lang.IllegalArgumentException: n must be positive in Sketched.scala

### ISSUE THREAD

**Issue by fdong-coursera** [twitter/scalding#1218]
Could `maxReplicas ` be ZERO? If this is ZERO, the following code 

`maxReplicas.ceil.toInt.min(numReducers)` will be zero and it triggers IllegalArgumentException when calling `rand.nextInt(n)` . 

https://github.com/twitter/scalding/blob/c8313b402a23dbe3cdaa103baac6622c7a043309/scalding-core/src/main/scala/com/twitter/scalding/typed/Sketched.scala#L107

Error stack as follows:
[error] Caused by: java.lang.IllegalArgumentException: n must be positive
[error]     at java.util.Random.nextInt(Random.java:300)
[error]     at scala.util.Random.nextInt(Random.scala:66)
[error]     at com.twitter.scalding.typed.SketchJoined$$anonfun$2.apply(Sketched.scala:115)
[error]     at com.twitter.scalding.typed.SketchJoined$$anonfun$2.apply(Sketched.scala:115)
[error]     at com.twitter.scalding.typed.SketchJoined$$anonfun$flatMapWithReplicas$1.apply(Sketched.scala:109)
[error]     at com.twitter.scalding.typed.SketchJoined$$anonfun$flatMapWithReplicas$1.apply(Sketched.scala:102)
[error]     at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error]     at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47)
[error]     at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
[error]     ... 34 more

Thanks.

**Comment by johnynek** [comment]
Thanks for the bug report. Yes the frequency could be zero if the key does not appear in the other side, and that means it is truly absent, so we don't need to send the key at all.

Can you reproduce this in a test? With such a test, it would be easy to fix (I can give you some pointers).

**Comment by oeddyo** [comment]
@johnynek I took a bit of time looking into this. I'm creating a test where a key only appears on one side but the test still passed. 

I must be missing something. Could you give me a pointer please :)

class TypedSketchJoinJobForEmptyKeys(args: Args) extends Job(args) {
  // Deal with when a key appears in left but not right
  val leftTypedPipe = TypedPipe.from(List((1, 1111), (2, 2222)))
  val rightTypedPipe = TypedPipe.from(List((3, 3333), (4, 4444)))

  implicit def serialize(k: Int) = k.toString.getBytes
  leftTypedPipe
    .sketch(1)
    .leftJoin(rightTypedPipe)
    .map{
      case (a, (b, c)) =>
        println("i'm fucking around here")
        (a, b, c.getOrElse(-1))
    }
    .write(TypedTsv[(Int, Int, Int)]("output-sketch"))

  leftTypedPipe
    .group
    .leftJoin(rightTypedPipe.group)
    .map{
      case (a, (b, c)) =>
        (a, b, c.getOrElse(-1))
    }
    .write(TypedTsv[(Int, Int, Int)]("output-join"))

}

**Comment by oeddyo** [comment]
@fdong-coursera It'd be great if you could help providing a test :) Appreciate that!

**Comment by GeeUnit** [comment]
Hi,

Has this issue been resolved/ re-produced?

If not, I might be able to shed some light, as I recently ran into this issue as well. There seems to be a bug which causes this error to be thrown when the left-side of your join (or in this case, a leftJoin) contains a pipe of a single object. In the above test case posted by @oeddyo, if you modify the left and right pipes to be,

val leftTypedPipe = TypedPipe.from(List((1, 1111)))
val rightTypedPipe = TypedPipe.from(List((3, 3333), (4, 4444)))

you'll run into the bug reported.

**Comment by johnynek** [comment]
@GeeUnit Thanks for the repro. Now we just need to add a failing test, and then fix the bug. Should be pretty easy now that we have this failing example.
