### ISSUE TITLE
scaladocs broken

### ISSUE THREAD

**Issue by declerambaul** [twitter/scalding#1350]
scalding (develop)]$ ./sbt unidoc

    [error]
    [error]   last tree to typer: Literal(Constant(cascading.pipe.Pipe))
    [error]               symbol: null
    [error]    symbol definition: null
    [error]                  tpe: Class(classOf[cascading.pipe.Pipe])
    [error]        symbol owners:
    [error]       context owners: trait WithReducers -> package typed
    [error]
    [error] == Enclosing template or block ==
    [error]
    [error] Template( // val <local WithReducers>: <notype> in trait WithReducers, tree.tpe=com.twitter.scalding.typed.WithReducers
    [error]   "java.lang.Object", "com.twitter.scalding.typed.HasReducers" // parents
    [error]   ValDef(
    [error]     private
    [error]     "_"
    [error]     <tpt>
    [error]     <empty>
    [error]   )
    [error]   DefDef( // def withReducers(reds: Int): com.twitter.scalding.typed.WithReducers in trait WithReducers
    [error]     <method> <deferred> <triedcooking>
    [error]     "withReducers"
    [error]     []
    [error]     // 1 parameter list
    [error]     ValDef( // reds: Int
    [error]       <param>
    [error]       "reds"
    [error]       <tpt> // tree.tpe=Int
    [error]       <empty>
    [error]     )
    [error]     <tpt> // tree.tpe=com.twitter.scalding.typed.WithReducers
    [error]     <empty>
    [error]   )
    [error] )
    [error]
    [error] == Expanded type of tree ==
    [error]
    [error] ConstantType(value = Constant(cascading.pipe.Pipe))
    [error]
    [error] uncaught exception during compilation: java.lang.AssertionError
    java.lang.AssertionError: assertion failed: List(object package$RichPathFilter, object package$RichPathFilter)
      at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:1678)
      at scala.reflect.internal.Symbols$ClassSymbol.companionModule0(Symbols.scala:2988)
      at scala.reflect.internal.Symbols$ClassSymbol.companionModule(Symbols.scala:2991)
      at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1371)
      at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:120)
      at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
      at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
      at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
      at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
      at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
      at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
      at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
      at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
      at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
      at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
      at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
      at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
      at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
      at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
      at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
      at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
      at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
      at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
      at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
      at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
      at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
      at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
      at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
      at sbt.inc.Incremental$.compile(Incremental.scala:61)
      at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
      at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
      at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
      at sbt.Compiler$.compile(Compiler.scala:128)
      at sbt.Compiler$.compile(Compiler.scala:114)
      at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
      at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
      at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
      at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
      at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
      at sbt.std.Transform$$anon$4.work(System.scala:63)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
      at sbt.Execute.work(Execute.scala:235)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
      at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:745)
    [error] (scalding-core/compile:compileIncremental) java.lang.AssertionError: assertion failed: List(object package$RichPathFilter, object package$RichPathFilter)
    [error] Total time: 105 s, completed Jul 2, 2015 12:39:17 PM

**Comment by johnynek** [comment]
Trying 2.11 seems to get past this compiler error, but hits another for me in scrooge-parquet:

```
[error] /Users/oscar/workspace/scalding/scalding-parquet-scrooge/src/main/scala/com/twitter/scalding/parquet/scrooge/ParquetScrooge.scala:3: object scrooge is not a member of package parquet
[error] import _root_.parquet.scrooge.ParquetScroogeScheme
[error]                       ^
[error] /Users/oscar/workspace/scalding/scalding-parquet-scrooge/src/main/scala/com/twitter/scalding/parquet/scrooge/ParquetScrooge.scala:13: not found: type ParquetScroogeScheme
[error]     val scheme = new ParquetScroogeScheme[T](this.config)
[error]                      ^
[info] No documentation generated with unsuccessful compiler run
[warn] 32 warnings found
[error] two errors found
[error] (scalding/*:unidoc) Scaladoc generation failed
[error] Total time: 252 s, completed Jul 6, 2015 10:32:43 AM
```

**Comment by declerambaul** [comment]
Had a quick look and you are right.

The parquet-scrooge dependency is only included for scala 2.10 (https://github.com/twitter/scalding/blob/develop/project/Build.scala#L361) - and they are not yet published for 2.11 it seems (http://mvnrepository.com/artifact/com.twitter/parquet-scrooge_2.10).

When compiling with 2.11.7 and forcing the parquet-scrooge 2.10 version, the unidoc target succeeds.
