### ISSUE TITLE
Can't run on local mode

### ISSUE THREAD

**Issue by QuantumBear** [twitter/scalding#1363]
After finish the "sbt assembly" command, then I try ./sbt "scalding-repl/run --local". Do I need pre-install something on my server?

[error] (run-main-0) java.lang.NoClassDefFoundError: cascading/flow/FlowConnector
java.lang.NoClassDefFoundError: cascading/flow/FlowConnector
        at com.twitter.scalding.Mode$.apply(Mode.scala:75)
        at com.twitter.scalding.BaseScaldingShell$class.parseModeArgs(ScaldingShell.scala:115)
        at com.twitter.scalding.ScaldingShell$.parseModeArgs(ScaldingShell.scala:194)
        at com.twitter.scalding.BaseScaldingShell$class.process(ScaldingShell.scala:66)
        at com.twitter.scalding.ScaldingShell$.process(ScaldingShell.scala:194)
        at com.twitter.scalding.BaseScaldingShell$class.main(ScaldingShell.scala:125)
        at com.twitter.scalding.ScaldingShell$.main(ScaldingShell.scala:194)
        at com.twitter.scalding.ScaldingShell.main(ScaldingShell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
Caused by: java.lang.ClassNotFoundException: cascading.flow.FlowConnector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.twitter.scalding.Mode$.apply(Mode.scala:75)
        at com.twitter.scalding.BaseScaldingShell$class.parseModeArgs(ScaldingShell.scala:115)
        at com.twitter.scalding.ScaldingShell$.parseModeArgs(ScaldingShell.scala:194)
        at com.twitter.scalding.BaseScaldingShell$class.process(ScaldingShell.scala:66)
        at com.twitter.scalding.ScaldingShell$.process(ScaldingShell.scala:194)
        at com.twitter.scalding.BaseScaldingShell$class.main(ScaldingShell.scala:125)
        at com.twitter.scalding.ScaldingShell$.main(ScaldingShell.scala:194)
        at com.twitter.scalding.ScaldingShell.main(ScaldingShell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last scalding-repl/unprovided:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last scalding-repl/*:run for the full output.
[error] (scalding-repl/*:run) Nonzero exit code: 1
[error] Total time: 2 s, completed Jul 15, 2015 12:41:23 PM

**Comment by johnynek** [comment]
works for me (you shouldn't need the sbt assembly command even).

What version of scalding have you checked out?

Are you running this on linux with encrypted home directory by chance (it limits file name lengths and silently causes problems, yay!). If not, what is your system setup?

**Comment by QuantumBear** [comment]
I use develop branch, top commit is fc4b4779bcec177533673b1e7481f27567f4b212. It contains such information "Merge: 27af5f2 1aad0bc
Author: Ian O'Connell <ianoconnell@gmail.com>
Date:   Tue Jul 14 10:52:51 2015 -0700

    Merge pull request #1362 from twitter/ianoc/HdfsTapCreationConfigurable

    Allow overriding of hadoop configuration options for a single source/…
"

My system is RH 5.3 and use JDK1.8.0_45.

I found sbt startup command is "+ exec /opt/jdk1.8.0_45//bin/java -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -jar /home/hadoop/.sbt/launchers/0.13.8/sbt-launch.jar warn 'set javaHome in ThisBuild := Some(file("/opt/jdk1.8.0_45/"))' info 'scalding-repl/run --local'

Do I need to pass the classpath here?

**Comment by johnynek** [comment]
Like I said, it "just works" for me.

You are using the sbt launcher script in the repo, right? It should be a
zero install/config setup.

I wonder if JDK 8 is an issue.

Can you try doing this again but checkout the repo into a /tmp (not a home
directory), just try to isolate possible filesystem issues.

The class it can't find is part of cascading, which is definitely in the
build, and if sbt is working correctly, it should not try to run without
that class (and sbt should setup the classpath).

On Wed, Jul 15, 2015 at 10:19 AM, Scott <notifications@github.com> wrote:

> I use develop branch, top commit is fc4b477
> <https://github.com/twitter/scalding/commit/fc4b4779bcec177533673b1e7481f27567f4b212>.
> It contains such information "Merge: 27af5f2
> <https://github.com/twitter/scalding/commit/27af5f2abf4c6aa898a5bd253100ba08bdb6c35e>
> 1aad0bc
> <https://github.com/twitter/scalding/commit/1aad0bc0f395d82a42a29b8f44377fd60f853cbc>
> Author: Ian O'Connell ianoconnell@gmail.com
> Date: Tue Jul 14 10:52:51 2015 -0700
>
> Merge pull request #1362 from twitter/ianoc/HdfsTapCreationConfigurable
>
> Allow overriding of hadoop configuration options for a single source/…
>
> "
>
> My system is RH 5.3 and use JDK1.8.0_45.
>
> I found sbt startup command is "+ exec /opt/jdk1.8.0_45//bin/java -Xms512m
> -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation
> -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -jar
> /home/hadoop/.sbt/launchers/0.13.8/sbt-launch.jar warn 'set javaHome in
> ThisBuild := Some(file("/opt/jdk1.8.0_45/"))' info 'scalding-repl/run
> --local'
>
> Do I need to pass the classpath here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/issues/1363#issuecomment-121630851>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by QuantumBear** [comment]
Fixed by switch to another user.
