### ISSUE TITLE
sbt test fail

### ISSUE THREAD

**Issue by QuantumBear** [twitter/scalding#1377]
Can we just mock this API? instead of reading the real local dir.

[info]   Cause: java.io.IOException: No valid local directories in property: mapreduce.cluster.local.dir
[info]   at org.apache.hadoop.conf.Configuration.getLocalPath(Configuration.java:2012)
[info]   at org.apache.hadoop.mapred.JobConf.getLocalPath(JobConf.java:567)
[info]   at org.apache.hadoop.mapred.LocalJobRunner$Job.<init>(LocalJobRunner.java:156)
[info]   at org.apache.hadoop.mapred.LocalJobRunner.submitJob(LocalJobRunner.java:731)
[info]   at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
[info]   at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
[info]   at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at javax.security.auth.Subject.doAs(Subject.java:422)
[info]   at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
[info]   at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
[info]   at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:562)
[info]   at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:557)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at javax.security.auth.Subject.doAs(Subject.java:422)
[info]   at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
[info]   at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:557)
[info]   at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:548)
[info]   at cascading.flow.hadoop.planner.HadoopFlowStepJob.internalNonBlockingStart(HadoopFlowStepJob.java:108)
[info]   at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:207)
[info]   at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:150)
[info]   at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
[info]   at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)

**Comment by ianoc** [comment]
Which test is failing ? Our test suite is showing green, maybe we have some
oversight

**Comment by QuantumBear** [comment]
I ran test-only com.twitter.scalding.typed.ExecutionTest in sbt console.

**Comment by ianoc** [comment]
That test is in our normal test suite and is working normally afaik. What
branch? os ?

**Comment by QuantumBear** [comment]
I just use develop branch, and my os is RH5.3.

**Comment by ianoc** [comment]
Is this the only test that fails for you? There is nothing unusual in this test in that we have lots of tests that use the same hadoop local mode provided by hadoop. 

Mocking isn't an option here as we exactly need the real hadoop interaction API's to ensure proper behavior. Probably something in the local FS if its not transient

**Comment by johnynek** [comment]
Does this machine have a writable `/tmp` directory?

**Comment by QuantumBear** [comment]
There are also some other tests fail because of this reason. I think the root cause may be something error in my local hadoop configuration, I will check it again.

**Comment by johnynek** [comment]
your hadoop configuration shouldn't come into this. The point of these tests is to start its own local hadoop. Maybe you already have hadoop running and this is conflicting?

You don't need anything installed or running to run our tests. Just type ./sbt test and it should download everything you need to run. You only need a jvm.
