### ISSUE TITLE
Multiple unit test failures (Ubuntu 64, Java7)

### ISSUE THREAD

**Issue by benjaminabbitt** [twitter/scalding#1445]
I'm new to Scalding, just trying to use it for the first time.  I'm following the instructions on the getting started page running the following commands after cloning the repos:

./sbt update
./sbt test     # runs the tests; if you do 'sbt assembly' below, these tests, which are long, are repeated
./sbt assembly # creates a fat jar with all dependencies, which is useful when using the scald.rb script

Unfortunately, I'm getting unit test failures on the most recent RC.

[Vagrantfile](https://parivedasolutions.box.com/s/q1h1o2puh1ol1xnqc7bv56cie1rr8ctt) that demonstrates the problem.
[Log](https://parivedasolutions.box.com/s/l7cabj96op2hkpoj29ip8ss8fc2yr9lp) file that shows the errors

Appreciate any feedback or suggestions.

**Comment by MansurAshraf** [comment]
This is probably an environment issue related to Vagrant as hadoop shell is failing with exit code 127. I suspect that if you run it directly without vagrant it will work

**Comment by benjaminabbitt** [comment]
Unfortunately, execution from within Vagrant from a bash prompt yields the same output.  In fact, the log was captured from a ssh session within Vagrant.

**Comment by johnynek** [comment]
Here is an example failure:

```
 1452 2015-09-28 20:52:01,520 WARN  [pool-51-thread-1] flow.FlowStep (BaseFlowStep.java:logWarn(839)) - [com.twitter.s calding.p...] failure info: Application application_1443473502129_0002 failed 2 times due to AM Container for appattem pt_1443473502129_0002_000002 exited with  exitCode: 127 due to: Exception from container-launch: ExitCodeException exi tCode=127:  1453 ExitCodeException exitCode=127:  1454         at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)  1455         at org.apache.hadoop.util.Shell.run(Shell.java:455)  1456         at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:702)  1457         at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerEx ecutor.java:195)  1458         at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLau nch.java:300)  1459         at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLau nch.java:81)  1460         at java.util.concurrent.FutureTask.run(FutureTask.java:262)  1461         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)  1462         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)  1463         at java.lang.Thread.run(Thread.java:745)  1464  1465  1466 Container exited with a non-zero exit code 127
```
It seems that when Hadoop shelled out, an error occurred. I wonder if there was some standard error output that is missed here that might give us a clue as to what is going on.

That said, you can run the tests for each sub-project:

try:
```
./sbt scalding-core/test
```
If that passes, it may just be our local hadoop tests that are failing, which don't matter for you to run. You can change the build to not run all the tests to make the assembly here:

https://github.com/twitter/scalding/blob/develop/project/Build.scala#L115

then you can build the assembly and use scald.rb to submit to your cluster (or preferably follow something like: https://github.com/soulmachine/scalding-example-project to just submit the job as you would any hadoop job, scald.rb isn't our finest software).
