### ISSUE TITLE
OrderedSerialization macros seem to fail on AnyVal case classes wrapping string

### ISSUE THREAD

**Issue by johnynek** [twitter/scalding#1517]
``` scala
ava.lang.UnsupportedOperationException: empty.reduceLeft
        at scala.collection.LinearSeqOptimized$class.reduceLeft(LinearSeqOptimized.scala:137)
        at scala.collection.immutable.List.reduceLeft(List.scala:84)
        at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:206)
        at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.ProductOrderedBuf$$anon$1.<init>
(ProductOrderedBuf.scala:116)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.ProductOrderedBuf$.apply(Product
OrderedBuf.scala:84)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.ProductOrderedBuf$$anonfun$1.app
lyOrElse(ProductOrderedBuf.scala:63)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.ProductOrderedBuf$$anonfun$1.app
lyOrElse(ProductOrderedBuf.scala:62)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.CaseObjectOrderedBuf$$anonfun$di
spatch$1.applyOrElse(CaseObjectOrderedBuf.scala:27)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.CaseObjectOrderedBuf$$anonfun$di
spatch$1.applyOrElse(CaseObjectOrderedBuf.scala:27)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.CaseClassOrderedBuf$$anonfun$dis
patch$1.applyOrElse(CaseClassOrderedBuf.scala:27)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.CaseClassOrderedBuf$$anonfun$dis
patch$1.applyOrElse(CaseClassOrderedBuf.scala:27)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.TraversablesOrderedBuf$$anonfun$
dispatch$1.applyOrElse(TraversablesOrderedBuf.scala:40)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.TraversablesOrderedBuf$$anonfun$
dispatch$1.applyOrElse(TraversablesOrderedBuf.scala:40)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.ByteBufferOrderedBuf$$anonfun$di
spatch$1.applyOrElse(ByteBufferOrderedBuf.scala:29)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.ByteBufferOrderedBuf$$anonfun$di
spatch$1.applyOrElse(ByteBufferOrderedBuf.scala:29)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at com.twitter.scalding.serialization.macros.impl.ordered_serialization.providers.StringOrderedBuf$$anonfun$dispat
ch$1.applyOrElse(StringOrderedBuf.scala:28)

```

/cc @ianoc

**Comment by ianoc** [comment]
Added a test, doesn't seem to want to fail...
https://github.com/twitter/scalding/compare/ianoc/testForAnyValCC?expand=1

**Comment by johnynek** [comment]
what about a tuple of these?

``` scala
case class A(name: String) extends AnyVal

// Does this work?
(A, A, A, A)
```

**Comment by ianoc** [comment]
Updated branch, appears to work ok
