### ISSUE TITLE
Develop branch CI failed for MacroOrderingProperties

### ISSUE THREAD

**Issue by isnotinvain** [twitter/scalding#1543]
https://travis-ci.org/twitter/scalding/jobs/120727552

I'm re-running to see if it's a flaky test or not.

```
[0m[[0minfo[0m] [0m[31m- Test out Array[Byte] *** FAILED ***[0m[0m
[0m[[0minfo[0m] [0m[31m  6 was not less than or equal to 3 (MacroOrderingProperties.scala:304)[0m[0m
[0m[[0minfo[0m] [0m[31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)[0m[0m
[0m[[0minfo[0m] [0m[31m  at com.twitter.scalding.serialization.macros.MacroOrderingProperties.checkCollisions(MacroOrderingProperties.scala:304)[0m[0m
[0m[[0minfo[0m] [0m[31m  at com.twitter.scalding.serialization.macros.MacroOrderingProperties$$anonfun$35.apply$mcV$sp(MacroOrderingProperties.scala:484)[0m[0m
[0m[[0minfo[0m] [0m[31m  at com.twitter.scalding.serialization.macros.MacroOrderingProperties$$anonfun$35.apply(MacroOrderingProperties.scala:481)[0m[0m
[0m[[0minfo[0m] [0m[31m  at com.twitter.scalding.serialization.macros.MacroOrderingProperties$$anonfun$35.apply(MacroOrderingProperties.scala:481)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.immutable.List.foreach(List.scala:381)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.Suite$class.run(Suite.scala:1424)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.FunSuite.run(FunSuite.scala:1555)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)[0m[0m
[0m[[0minfo[0m] [0m[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:294)[0m[0m
[0m[[0minfo[0m] [0m[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:284)[0m[0m
[0m[[0minfo[0m] [0m[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:262)[0m[0m
[0m[[0minfo[0m] [0m[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[0m[0m
[0m[[0minfo[0m] [0m[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[0m[0m
[0m[[0minfo[0m] [0m[31m  at java.lang.Thread.run(Thread.java:745)[0m[0m
```

**Comment by isnotinvain** [comment]
Is there a way to find out what inputs were used for this failed property check? @johnynek @ianoc  ?

**Comment by johnynek** [comment]
scalacheck should print them, but I guess either the way we have configured that or scalatest is hiding them.

That is a statistical check about collisions in a hash. Not sure the best way to test that, but it can probably be improved.

**Comment by isnotinvain** [comment]
Yeah couldn't find it in the logs :(
So you don't think this is a fatal error? It is somewhat expected to be flaky?

**Comment by johnynek** [comment]
I think it may be flaky, yes.

**Comment by johnynek** [comment]
in that, it is testing a property that is not true with 100% probability.

**Comment by isnotinvain** [comment]
OK SGMT. Is it something we can change to make it more like 99.99999999% probability?
